<script lang="ts">
	import { Accordion as AccordionPrimitive } from 'bits-ui';
	import { cn } from '$lib/utils.js';

	let {
		ref = $bindable(null),
		value = $bindable(),
		class: className,
		...restProps
	}: AccordionPrimitive.RootProps = $props();
</script>

<!--
	Heads up when restyling this accordion: it is also embedded inline by the
	reasoning/thinking block (ai-elements/reasoning), which expects a flat,
	chromeless accordion. Card chrome added here (border, radius, open fill, ring,
	shadow) leaks into that block. The reasoning component opts out of
	border/radius/open-fill in Reasoning.svelte; extend that opt-out for any new
	chrome, or this file may be regenerated by `shadcn add` and wipe this note.
-->
<AccordionPrimitive.Root
	bind:ref
	bind:value={value as never}
	data-slot="accordion"
	class={cn('cn-accordion flex w-full flex-col', className)}
	{...restProps}
/>
