export const MARKDOWN_ACCEPT_FIXTURES = [
	{ value: null, expected: false },
	{ value: '', expected: false },
	{ value: 'text/html', expected: false },
	{ value: 'text/markdown', expected: true },
	{ value: 'TEXT/MARKDOWN; charset=utf-8', expected: true },
	{ value: 'text/markdown; charset="UTF-8"', expected: true },
	{ value: 'text/markdown; charset=iso-8859-1', expected: false },
	{ value: 'text/markdown;constructor=x', expected: false },
	{ value: 'text/markdown;__proto__=x', expected: false },
	{ value: 'text/markdown;q=0.8;charset=iso-8859-1, text/html;q=0.5', expected: false },
	{ value: 'text/html, text/markdown;q=0.5', expected: false },
	{ value: 'text/html;q=0.5, text/markdown', expected: true },
	{ value: 'text/*', expected: false },
	{ value: 'text/*;q=1, text/html;q=0', expected: true },
	{ value: '*/*', expected: false },
	{ value: '*/*;q=0.5, text/markdown;q=0.8', expected: true },
	{ value: 'text/markdown;q=0', expected: false },
	{ value: 'text/markdown;q=0.000', expected: false },
	{ value: 'text/markdown;q=1.001', expected: false },
	{ value: 'text/markdown;q=wat', expected: false },
	{ value: 'application/json; note="text/markdown"', expected: false },
	{ value: 'application/json; note="a,b", text/markdown;q=0.8', expected: true }
] as const;
