// Generated by `bun run i18n:sync`. Edit languages.ts and locale JSON files instead.
import fallback from '../../i18n/en.json';
import de from '../../i18n/de.json?url';
import es from '../../i18n/es.json?url';
import fr from '../../i18n/fr.json?url';
import type { LanguageCode } from './languages';

export const FALLBACK_TRANSLATIONS = { en: fallback };

export const TRANSLATION_URLS = {
	de,
	es,
	fr
} satisfies Partial<Record<LanguageCode, string>>;
