/**
 * Build script for email templates
 *
 * This script starts a temporary Vite dev server, renders email templates
 * via the API endpoint, and generates TypeScript files for Convex.
 *
 * Run with: bun run build:emails
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, type ChildProcess } from 'node:child_process';
import { EMAIL_TEMPLATES, getOutputFileName } from '../src/lib/emails/templates/registry';

const __scriptDir = dirname(fileURLToPath(import.meta.url));
const GENERATED_DIR = join(__scriptDir, '../src/lib/convex/emails/_generated');
const DEV_SERVER_PORT = 5199; // Use non-standard port to avoid conflicts
const DEV_SERVER_URL = `http://localhost:${DEV_SERVER_PORT}`;
const BUILD_ENDPOINT = `${DEV_SERVER_URL}/api/emails/build`;

/**
 * Escapes backticks and ${} in strings for use in template literals
 */
function escapeTemplateLiteral(str: string): string {
	return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

/**
 * Generates a TypeScript file with exported HTML and text constants
 */
function generateTemplateFile(name: string, html: string, text: string): string {
	const escapedHtml = escapeTemplateLiteral(html);
	const escapedText = escapeTemplateLiteral(text);

	return `// Auto-generated by scripts/build-emails.ts - DO NOT EDIT
// Regenerate with: bun run build:emails

export const ${name.toUpperCase()}_HTML = \`${escapedHtml}\`;

export const ${name.toUpperCase()}_TEXT = \`${escapedText}\`;
`;
}

/**
 * Wait for the dev server to be ready
 */
async function waitForServer(url: string, maxAttempts = 30): Promise<void> {
	for (let i = 0; i < maxAttempts; i++) {
		try {
			const response = await fetch(url, { method: 'HEAD' });
			if (response.ok || response.status === 404) {
				return; // Server is ready
			}
		} catch {
			// Server not ready yet
		}
		await new Promise((resolve) => setTimeout(resolve, 1000));
	}
	throw new Error(`Server did not become ready at ${url} after ${maxAttempts} attempts`);
}

/**
 * Start the Vite dev server
 */
function startDevServer(): ChildProcess {
	const child = spawn('bunx', ['vite', 'dev', '--port', DEV_SERVER_PORT.toString()], {
		stdio: ['ignore', 'pipe', 'pipe'],
		cwd: process.cwd(),
		detached: false
	});

	child.stdout?.on('data', (data) => {
		const output = data.toString();
		if (output.includes('Local:')) {
			// Server started
		}
	});

	child.stderr?.on('data', (data) => {
		// Only log actual errors, not warnings
		const output = data.toString();
		if (output.includes('error') || output.includes('Error')) {
			console.error('Dev server error:', output);
		}
	});

	return child;
}

/**
 * Stop the dev server gracefully, with a timeout fallback
 */
async function stopDevServer(devServer: ChildProcess, timeout = 5000): Promise<void> {
	return new Promise((resolve) => {
		const timeoutId = setTimeout(() => {
			// Force kill if graceful shutdown takes too long
			devServer.kill('SIGKILL');
			resolve();
		}, timeout);

		devServer.on('close', () => {
			clearTimeout(timeoutId);
			resolve();
		});

		// Send graceful shutdown signal
		devServer.kill('SIGTERM');
	});
}

async function buildEmails() {
	// Check if PUBLIC_CONVEX_URL is available (required for dev server to start)
	if (!process.env.PUBLIC_CONVEX_URL) {
		console.log('⏭️  Skipping email template build - PUBLIC_CONVEX_URL not set');
		console.log('');
		console.log('   This is expected during initial install or CI.');
		console.log('   Email templates will be built during the actual build step.');
		console.log('');
		console.log('   To build manually after setting up .env.local:');
		console.log('   bun run build:emails');
		console.log('');
		return;
	}

	console.log('Building email templates...\n');

	// Ensure generated directory exists
	if (!existsSync(GENERATED_DIR)) {
		mkdirSync(GENERATED_DIR, { recursive: true });
		console.log(`Created directory: ${GENERATED_DIR}`);
	}

	// Start temporary dev server
	console.log('  Starting temporary dev server...');
	const devServer = startDevServer();

	try {
		// Wait for server to be ready
		await waitForServer(DEV_SERVER_URL);
		console.log('  Dev server ready.\n');

		// Call the API endpoint to render all templates
		const response = await fetch(BUILD_ENDPOINT, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({})
		});

		if (!response.ok) {
			throw new Error(`API request failed: ${response.status} ${response.statusText}`);
		}

		const { templates } = (await response.json()) as {
			templates: Array<{
				name: string;
				html?: string;
				text?: string;
				error?: string;
				success: boolean;
			}>;
		};

		const results: { name: string; success: boolean; error?: string }[] = [];

		for (const template of templates) {
			const fileName = getOutputFileName(template.name);

			if (template.success && template.html && template.text) {
				console.log(`  Rendering ${template.name}...`);

				// Generate TypeScript file content
				const fileContent = generateTemplateFile(fileName, template.html, template.text);

				// Write to file
				const filePath = join(GENERATED_DIR, `${fileName}.ts`);
				writeFileSync(filePath, fileContent, 'utf-8');

				console.log(
					`    -> Generated ${fileName}.ts (${template.html.length} chars HTML, ${template.text.length} chars text)`
				);
				results.push({ name: template.name, success: true });
			} else {
				console.error(`    -> Error rendering ${template.name}: ${template.error}`);
				results.push({ name: template.name, success: false, error: template.error });
			}
		}

		// Generate index file that exports all templates dynamically
		const exportStatements = Object.values(EMAIL_TEMPLATES)
			.map((config) => `export * from './${config.outputName}.js';`)
			.join('\n');
		const indexContent = `// Auto-generated by scripts/build-emails.ts - DO NOT EDIT

${exportStatements}
`;
		writeFileSync(join(GENERATED_DIR, 'index.ts'), indexContent, 'utf-8');

		// Summary
		console.log('\n--- Build Summary ---');
		const successful = results.filter((r) => r.success).length;
		const failed = results.filter((r) => !r.success).length;
		console.log(`  Successful: ${successful}`);
		console.log(`  Failed: ${failed}`);

		if (failed > 0) {
			console.error('\nFailed templates:');
			for (const result of results.filter((r) => !r.success)) {
				console.error(`  - ${result.name}: ${result.error}`);
			}
			process.exit(1);
		}

		console.log('\nEmail templates built successfully!');
	} finally {
		// Always stop the dev server
		console.log('\n  Stopping dev server...');
		await stopDevServer(devServer);
	}
}

buildEmails();
