/**
 * Build script for email templates
 *
 * Calls the SvelteKit API endpoint to render email templates with Eta placeholders.
 * The generated files are used by Convex to send emails with dynamic content.
 *
 * Requirements:
 * 1. The dev server must be running: bun run dev:frontend
 * 2. Or run during the build process
 *
 * Run with: bun scripts/build-emails.ts
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __scriptDir = dirname(fileURLToPath(import.meta.url));
const GENERATED_DIR = join(__scriptDir, '../src/lib/convex/emails/generated');

// Map from API template names to file names
const TEMPLATE_NAME_MAP: Record<string, string> = {
	VerificationEmail: 'verification',
	PasswordResetEmail: 'passwordReset',
	AdminReplyNotificationEmail: 'adminReplyNotification'
};

/**
 * Escapes backticks and ${} in strings for use in template literals
 */
function escapeTemplateLiteral(str: string): string {
	return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

/**
 * Generates a TypeScript file with exported HTML and text constants
 */
function generateTemplateFile(name: string, html: string, text: string): string {
	const escapedHtml = escapeTemplateLiteral(html);
	const escapedText = escapeTemplateLiteral(text);

	return `// Auto-generated by scripts/build-emails.ts - DO NOT EDIT
// Regenerate with: bun scripts/build-emails.ts

export const ${name.toUpperCase()}_HTML = \`${escapedHtml}\`;

export const ${name.toUpperCase()}_TEXT = \`${escapedText}\`;
`;
}

async function buildEmails() {
	const baseUrl = process.env.BUILD_EMAIL_URL || 'http://localhost:5173';
	const endpoint = `${baseUrl}/api/emails/build`;

	console.log('Building email templates...');
	console.log(`  Using endpoint: ${endpoint}\n`);

	// Ensure generated directory exists
	if (!existsSync(GENERATED_DIR)) {
		mkdirSync(GENERATED_DIR, { recursive: true });
		console.log(`Created directory: ${GENERATED_DIR}`);
	}

	try {
		// Call the API endpoint to render all templates
		const response = await fetch(endpoint, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({})
		});

		if (!response.ok) {
			throw new Error(`API request failed: ${response.status} ${response.statusText}`);
		}

		const { templates } = (await response.json()) as {
			templates: Array<{
				name: string;
				html?: string;
				text?: string;
				error?: string;
				success: boolean;
			}>;
		};

		const results: { name: string; success: boolean; error?: string }[] = [];

		for (const template of templates) {
			const fileName = TEMPLATE_NAME_MAP[template.name] || template.name.toLowerCase();

			if (template.success && template.html && template.text) {
				console.log(`  Rendering ${template.name}...`);

				// Generate TypeScript file content
				const fileContent = generateTemplateFile(fileName, template.html, template.text);

				// Write to file
				const filePath = join(GENERATED_DIR, `${fileName}.ts`);
				writeFileSync(filePath, fileContent, 'utf-8');

				console.log(
					`    -> Generated ${fileName}.ts (${template.html.length} chars HTML, ${template.text.length} chars text)`
				);
				results.push({ name: template.name, success: true });
			} else {
				console.error(`    -> Error rendering ${template.name}: ${template.error}`);
				results.push({ name: template.name, success: false, error: template.error });
			}
		}

		// Generate index file that exports all templates
		const indexContent = `// Auto-generated by scripts/build-emails.ts - DO NOT EDIT

export * from './verification.js';
export * from './passwordReset.js';
export * from './adminReplyNotification.js';
`;
		writeFileSync(join(GENERATED_DIR, 'index.ts'), indexContent, 'utf-8');

		// Summary
		console.log('\n--- Build Summary ---');
		const successful = results.filter((r) => r.success).length;
		const failed = results.filter((r) => !r.success).length;
		console.log(`  Successful: ${successful}`);
		console.log(`  Failed: ${failed}`);

		if (failed > 0) {
			console.error('\nFailed templates:');
			for (const result of results.filter((r) => !r.success)) {
				console.error(`  - ${result.name}: ${result.error}`);
			}
			process.exit(1);
		}

		console.log('\nEmail templates built successfully!');
	} catch (error) {
		console.error('Build failed:', error);
		console.error('\nMake sure the dev server is running: bun run dev:frontend');
		process.exit(1);
	}
}

buildEmails();
