/**
 * Build script for email templates
 *
 * This script uses Vite's programmatic API to render email templates
 * and generates TypeScript files for Convex.
 *
 * Run with: bun run build:emails
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer, type ViteDevServer } from 'vite';
import {
	EMAIL_TEMPLATES,
	getOutputFileName,
	getTemplatesForRendering
} from '../src/lib/emails/templates/registry';

const __scriptDir = dirname(fileURLToPath(import.meta.url));
const GENERATED_DIR = join(__scriptDir, '../src/lib/convex/emails/_generated');
const TEMPLATES_PATH = '/src/lib/emails/templates';

/**
 * Escapes backticks and ${} in strings for use in template literals
 */
function escapeTemplateLiteral(str: string): string {
	return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

/**
 * Generates a TypeScript file with exported HTML and text constants
 */
function generateTemplateFile(name: string, html: string, text: string): string {
	const escapedHtml = escapeTemplateLiteral(html);
	const escapedText = escapeTemplateLiteral(text);

	return `// Auto-generated by scripts/build-emails.ts - DO NOT EDIT
// Regenerate with: bun run build:emails

export const ${name.toUpperCase()}_HTML = \`${escapedHtml}\`;

export const ${name.toUpperCase()}_TEXT = \`${escapedText}\`;
`;
}

/**
 * Convert __ETA_xxx__ markers to {{xxx}} template syntax
 * Also converts __BASEURL__ to {{baseUrl}}
 */
function convertMarkersToTemplate(html: string): string {
	return html.replace(/__ETA_(\w+)__/g, '{{$1}}').replace(/__BASEURL__/g, '{{baseUrl}}');
}

/**
 * Create Vite server in middleware mode (no HTTP server)
 */
async function createViteServer(): Promise<ViteDevServer> {
	return createServer({
		server: { middlewareMode: true },
		appType: 'custom',
		logLevel: 'warn',
		ssr: {
			// Bundle better-svelte-email to handle CJS/ESM interop
			noExternal: ['better-svelte-email', 'prettier']
		}
	});
}

async function buildEmails() {
	// Check if PUBLIC_CONVEX_URL is available (required for dev server to start)
	if (!process.env.PUBLIC_CONVEX_URL) {
		console.log('⏭️  Skipping email template build - PUBLIC_CONVEX_URL not set');
		console.log('');
		console.log('   This is expected during initial install or CI.');
		console.log('   Email templates will be built during the actual build step.');
		console.log('');
		console.log('   To build manually after setting up .env.local:');
		console.log('   bun run build:emails');
		console.log('');
		return;
	}

	console.log('Building email templates...\n');

	// Ensure generated directory exists
	if (!existsSync(GENERATED_DIR)) {
		mkdirSync(GENERATED_DIR, { recursive: true });
		console.log(`Created directory: ${GENERATED_DIR}`);
	}

	// Create Vite server in middleware mode (no HTTP server needed)
	console.log('  Initializing Vite...');
	const vite = await createViteServer();

	try {
		// Load dependencies via ssrLoadModule
		const { renderer } = (await vite.ssrLoadModule('/src/lib/emails/renderer.ts')) as {
			renderer: { render: (component: unknown, options: { props: unknown }) => Promise<string> };
		};
		const { getEmailComponent } = (await vite.ssrLoadModule('better-svelte-email/preview')) as {
			getEmailComponent: (path: string, name: string) => Promise<unknown>;
		};
		const { toPlainText } = (await vite.ssrLoadModule('better-svelte-email/render')) as {
			toPlainText: (html: string) => string;
		};

		console.log('  Vite ready.\n');

		const templatesToRender = getTemplatesForRendering();
		const results: { name: string; success: boolean; error?: string }[] = [];

		for (const { name, props } of templatesToRender) {
			try {
				console.log(`  Rendering ${name}...`);

				// Get the template component
				const component = await getEmailComponent(TEMPLATES_PATH, name);

				// Render with marker props
				const rawHtml = await renderer.render(component, { props });
				const rawText = toPlainText(rawHtml);

				// Convert markers to template syntax
				const html = convertMarkersToTemplate(rawHtml);
				const text = convertMarkersToTemplate(rawText);

				// Get output filename
				const fileName = getOutputFileName(name);

				// Generate TypeScript file content
				const fileContent = generateTemplateFile(fileName, html, text);

				// Write to file
				const filePath = join(GENERATED_DIR, `${fileName}.ts`);
				writeFileSync(filePath, fileContent, 'utf-8');

				console.log(
					`    -> Generated ${fileName}.ts (${html.length} chars HTML, ${text.length} chars text)`
				);
				results.push({ name, success: true });
			} catch (err) {
				const errorMessage = err instanceof Error ? err.message : String(err);
				console.error(`    -> Error rendering ${name}: ${errorMessage}`);
				results.push({ name, success: false, error: errorMessage });
			}
		}

		// Generate index file that exports all templates dynamically
		const exportStatements = Object.values(EMAIL_TEMPLATES)
			.map((config) => `export * from './${config.outputName}.js';`)
			.join('\n');
		const indexContent = `// Auto-generated by scripts/build-emails.ts - DO NOT EDIT

${exportStatements}
`;
		writeFileSync(join(GENERATED_DIR, 'index.ts'), indexContent, 'utf-8');

		// Summary
		console.log('\n--- Build Summary ---');
		const successful = results.filter((r) => r.success).length;
		const failed = results.filter((r) => !r.success).length;
		console.log(`  Successful: ${successful}`);
		console.log(`  Failed: ${failed}`);

		if (failed > 0) {
			console.error('\nFailed templates:');
			for (const result of results.filter((r) => !r.success)) {
				console.error(`  - ${result.name}: ${result.error}`);
			}
			process.exit(1);
		}

		console.log('\nEmail templates built successfully!');
	} finally {
		// Always close Vite
		await vite.close();
	}
}

buildEmails();
