#!/usr/bin/env bun

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SUPPORT_SOURCE = path.join(PROJECT_ROOT, 'src/lib/convex/support/instructions.txt');
const SUPPORT_OUTPUT = path.join(PROJECT_ROOT, 'src/lib/convex/support/instructions.generated.ts');

export function renderGeneratedSupportInstructions(source: string): string {
	const normalizedSource = source.replace(/\r\n?/g, '\n').replace(/\n$/, '');
	return `// Generated by scripts/generate-authored-content.ts. Do not edit.\nexport const SUPPORT_AGENT_INSTRUCTIONS_TEMPLATE = ${JSON.stringify(normalizedSource)};\n`;
}

export function generateAuthoredContent(): void {
	const generated = renderGeneratedSupportInstructions(readFileSync(SUPPORT_SOURCE, 'utf8'));
	mkdirSync(path.dirname(SUPPORT_OUTPUT), { recursive: true });
	if (!existsSync(SUPPORT_OUTPUT) || readFileSync(SUPPORT_OUTPUT, 'utf8') !== generated) {
		writeFileSync(SUPPORT_OUTPUT, generated);
	}
}

if (import.meta.main) {
	generateAuthoredContent();
}
