
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

/* eslint-disable */
export type CoercedEnvSchema = {
  /**
   * **VARLOCK_ENV**  
   * Current environment, auto-detected from platform  
   */
  VARLOCK_ENV?: "development" | "preview" | "production" | "test";
  
  /**
   * **CONVEX_DEPLOYMENT** 🔐 _sensitive_  
   * Local dev deployment identifier, auto-set by `bunx convex dev`  
   */
  CONVEX_DEPLOYMENT?: string;
  
  /**
   * **PUBLIC_CONVEX_URL**  
   * Convex deployment API URL  
   */
  PUBLIC_CONVEX_URL?: string;
  
  /**
   * **PUBLIC_CONVEX_SITE_URL**  
   * Convex HTTP actions URL (for Better Auth)  
   */
  PUBLIC_CONVEX_SITE_URL?: string;
  
  /**
   * **CONVEX_INTERNAL_URL** 🔐 _sensitive_  
   * Internal Convex URL for server-side requests inside private Docker networks  
   * Example: http://convex:3210  
   */
  CONVEX_INTERNAL_URL?: string;
  
  /**
   * **VITE_TOLGEE_API_URL**  
   * Tolgee Cloud API URL  
   */
  VITE_TOLGEE_API_URL: string;
  
  /**
   * **VITE_TOLGEE_API_KEY**  
   * Tolgee project API key for DevTools in-context editing (exposed to browser via VITE_ prefix)  
   */
  VITE_TOLGEE_API_KEY?: string;
  
  /**
   * **TOLGEE_API_KEY** 🔐 _sensitive_  
   * Tolgee CLI API key for deploy-time tag/pull (server-side, not exposed to browser)  
   * When unset, the deploy script skips Tolgee sync and uses committed JSON files  
   */
  TOLGEE_API_KEY?: string;
  
  /**
   * **AUTUMN_SECRET_KEY** 🔐 _sensitive_  
   * Autumn billing test/dev secret key  
   */
  AUTUMN_SECRET_KEY?: string;
  
  /**
   * **AUTUMN_PROD_SECRET_KEY** 🔐 _sensitive_  
   * Autumn billing production secret key  
   */
  AUTUMN_PROD_SECRET_KEY?: string;
  
  /**
   * **PUBLIC_POSTHOG_API_KEY**  
   * PostHog project API key (client-safe)  
   */
  PUBLIC_POSTHOG_API_KEY?: string;
  
  /**
   * **PUBLIC_POSTHOG_HOST**  
   * PostHog ingestion endpoint  
   */
  PUBLIC_POSTHOG_HOST?: string;
  
  /**
   * **PUBLIC_POSTHOG_PROXY_HOST**  
   * Cloudflare Worker proxy for ad-blocker bypass  
   */
  PUBLIC_POSTHOG_PROXY_HOST?: string;
  
  /**
   * **PUBLIC_SNAPDOM_PROXY_URL**  
   * CORS proxy for external images in screenshots  
   */
  PUBLIC_SNAPDOM_PROXY_URL?: string;
  
  /**
   * **AUTH_E2E_TEST_SECRET** 🔐 _sensitive_  
   * Secret for test mutations (must match Convex backend)  
   */
  AUTH_E2E_TEST_SECRET?: string;
  
  /**
   * **PUBLIC_SITE_URL**  
   * Site URL for test requests (defaults to localhost:5173)  
   */
  PUBLIC_SITE_URL?: string;
  
  /**
   * **CONVEX_DEPLOY_KEY** 🔐 _sensitive_  
   * Convex deploy key for production deployments  
   */
  CONVEX_DEPLOY_KEY?: string;
  
  /**
   * **CONVEX_PREVIEW_DEPLOY_KEY** 🔐 _sensitive_  
   * Convex preview deploy key for preview deployments  
   * Generate from Convex dashboard > Preview Deploy Keys  
   */
  CONVEX_PREVIEW_DEPLOY_KEY?: string;
  
  /**
   * **NODE_ADAPTER**  
   * Set to "1" to build with adapter-node for self-hosted deployments  
   */
  NODE_ADAPTER?: string;
  
  /**
   * **PREVIEW_BYPASS_SECRET** 🔐 _sensitive_  
   * Preview bypass secret (maps to Vercel's VERCEL_AUTOMATION_BYPASS_SECRET in CI)  
   */
  PREVIEW_BYPASS_SECRET?: string;
  
  /**
   * **CF_ACCESS_CLIENT_ID** 🔐 _sensitive_  
   * Cloudflare Access service token client ID (for protected CF previews)  
   */
  CF_ACCESS_CLIENT_ID?: string;
  
  /**
   * **CF_ACCESS_CLIENT_SECRET** 🔐 _sensitive_  
   * Cloudflare Access service token client secret (for protected CF previews)  
   */
  CF_ACCESS_CLIENT_SECRET?: string;
  
  /**
   * **VERCEL_ENV**  
   * Vercel environment (injected by Vercel, read by deploy script)  
   */
  VERCEL_ENV?: "development" | "preview" | "production";
  
  /**
   * **VERCEL_URL**  
   * Vercel deployment URL (injected by Vercel, read by deploy script)  
   */
  VERCEL_URL?: string;
  
  /**
   * **VERCEL_GIT_COMMIT_REF**  
   * Git branch ref (injected by Vercel, read by deploy script)  
   */
  VERCEL_GIT_COMMIT_REF?: string;
  
  /**
   * **WORKERS_CI**  
   * Set to "1" by CF Workers Builds (injected by CF, read by deploy script)  
   */
  WORKERS_CI?: string;
  
  /**
   * **WORKERS_CI_BRANCH**  
   * Git branch (injected by CF Workers Builds, read by deploy script)  
   */
  WORKERS_CI_BRANCH?: string;
  
  /**
   * **WORKERS_CI_COMMIT_SHA**  
   * Commit SHA (injected by CF Workers Builds)  
   */
  WORKERS_CI_COMMIT_SHA?: string;
  
  /**
   * **WORKERS_NAME**  
   * Worker name (must match wrangler.toml name, used for preview URL construction)  
   */
  WORKERS_NAME?: string;
  
  /**
   * **WORKERS_SUBDOMAIN**  
   * Account's workers.dev subdomain (e.g., "daniel-ce4", used for preview URL construction)  
   */
  WORKERS_SUBDOMAIN?: string;
  
  /**
   * **CF_PAGES**  
   * Set to "1" by CF Pages (legacy, injected by CF, read by deploy script)  
   */
  CF_PAGES?: string;
  
  /**
   * **CF_PAGES_URL**  
   * Deployment URL (injected by CF Pages, full URL with https://)  
   */
  CF_PAGES_URL?: string;
  
  /**
   * **CF_PAGES_BRANCH**  
   * Git branch (injected by CF Pages, read by deploy script)  
   */
  CF_PAGES_BRANCH?: string;
  
  /**
   * **PRODUCTION_BRANCH**  
   * Production branch name (defaults to "main")  
   */
  PRODUCTION_BRANCH?: string;
  
  /**
   * **CI**  
   * Set to "true" in CI environments (injected by GitHub Actions)  
   */
  CI?: string;
  
  /**
   * **RESEND_API_KEY** 🔐 _sensitive_  
   * Resend API key for local email preview sending  
   */
  RESEND_API_KEY?: string;
  
  /**
   * **AUTH_EMAIL** 🔐 _sensitive_  
   * Sender email address for auth emails (signup, verification, password reset)  
   * Set via: bunx convex env set AUTH_EMAIL noreply@yourdomain.com  
   */
  AUTH_EMAIL?: string;
  
};


declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<CoercedEnvSchema> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<CoercedEnvSchema, 'VARLOCK_ENV' | 'PUBLIC_CONVEX_URL' | 'PUBLIC_CONVEX_SITE_URL' | 'VITE_TOLGEE_API_URL' | 'VITE_TOLGEE_API_KEY' | 'PUBLIC_POSTHOG_API_KEY' | 'PUBLIC_POSTHOG_HOST' | 'PUBLIC_POSTHOG_PROXY_HOST' | 'PUBLIC_SNAPDOM_PROXY_URL' | 'PUBLIC_SITE_URL' | 'NODE_ADAPTER' | 'VERCEL_ENV' | 'VERCEL_URL' | 'VERCEL_GIT_COMMIT_REF' | 'WORKERS_CI' | 'WORKERS_CI_BRANCH' | 'WORKERS_CI_COMMIT_SHA' | 'WORKERS_NAME' | 'WORKERS_SUBDOMAIN' | 'CF_PAGES' | 'CF_PAGES_URL' | 'CF_PAGES_BRANCH' | 'PRODUCTION_BRANCH' | 'CI'>> {}
}


export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};

declare global {

  // add types for global import.meta.env
  interface ImportMetaEnv extends EnvSchemaAsStrings {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends EnvSchemaAsStrings {}
  }
}